### ISSUE TITLE
Add moar info

### ISSUE THREAD

**Issue by giuseppeg** [jkup/sf-javascript-meetups#3]
It would be nice to covert the list to a table and add more info like:
- frequency (weekly/monthly/every 2nd week)
- supershort description
- ???

**Comment by jkup** [comment]
Yeah I think this would be awesome! PRs welcome but I'll start adding that stuff tonight :)

**Comment by jkup** [comment]
Done!

**Comment by giuseppeg** [comment]
:heart:  :+1:
