### ISSUE TITLE
Two more?

### ISSUE THREAD

**Issue by feesh** [jkup/sf-javascript-meetups#9]
Hi there! Heard of these two JS meetups recently, though I'm not sure what their meetup schedule is. Thanks for organizing this list!
- [DogpatchJS](http://dogpatchjs.com) — every Tuesday
- [ChocolateJS](http://chocolatejs.com/) — TBA

**Comment by feesh** [comment]
Not sure how to add the PR, but here's the markdown for adding those two!

```
[ChocolateJS]       |  TBA      | A place to celebrate the usually uninvited faces in tech.
[DogpatchJS]        |  Monthly  | A weekly free + public hangout in San Francisco, CA.


[ChocolateJS]: http://chocolatejs.com/
[DogpatchJS]: http://dogpatchjs.com/
```

**Comment by jkup** [comment]
Added! Thanks! :)
